// Cloudflare AllowMe: API client

import logger = require("anyhow")
import settings = require("./settings")
import axios, {AxiosRequestConfig} from "axios"

/**
 * Get account ID from Cloudflare.
 */
export const getAccountId = async (): Promise<string> => {
    try {
        const res: any[] = await makeRequest("accounts")

        if (res.length > 0) {
            logger.info("Cloudflare.getAccountId", res[0].id)
            return res[0].id
        } else {
            throw new Error("No accounts allowed for the current token")
        }
    } catch (ex) {
        logger.error("Cloudflare.getAccountId", ex)
    }
}

/**
 * Get zone ID from Cloudflare.
 */
export const getZoneId = async (): Promise<string> => {
    try {
        const res: any[] = await makeRequest(`zones?name=${settings.cloudflare.zone}`)

        if (res.length > 0) {
            logger.info("Cloudflare.getZoneId", res[0].id)
            return res[0].id
        } else {
            throw new Error(`Invalid zone: ${settings.cloudflare.zone}`)
        }
    } catch (ex) {
        logger.error("Cloudflare.getZoneId", ex)
    }
}

/**
 * Get list ID from Cloudflare.
 */
export const getListId = async (): Promise<string> => {
    try {
        const res: any[] = await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists`)
        const list = res.find((i) => i.name == "allowme" && i.kind == "ip")

        if (list) {
            logger.info("Cloudflare.getListId", list.id)
            return list.id
        } else if (res.length == 0) {
            const listId = await createList()
            logger.info("Cloudflare.getListId", listId)
            return listId
        } else {
            throw new Error(`No "allowme" IP list was found`)
        }
    } catch (ex) {
        logger.error("Cloudflare.getListId", ex)
    }
}

/**
 * Get list name from Cloudflare, in case a list ID was directly set.
 */
export const getListName = async (): Promise<string> => {
    try {
        const res: any = await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists/${settings.cloudflare.listId}`)

        if (res) {
            logger.info("Cloudflare.getListName", res.name)
            return res.name
        } else {
            throw new Error(`Invalid list ID: ${settings.cloudflare.listId}`)
        }
    } catch (ex) {
        logger.error("Cloudflare.getListName", ex)
    }
}

/**
 * Get the IPs from the list on Cloudflare.
 */
export const getListItems = async (): Promise<any[]> => {
    try {
        const res: any[] = await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists/${settings.cloudflare.listId}/items`)

        if (res) {
            return res
        } else {
            throw new Error(`No list IPs were returned`)
        }
    } catch (ex) {
        logger.error("Cloudflare.getListItems", ex)
    }
}

/**
 * Create an "allowme" IP list on Cloudflare.
 */
export const createList = async (): Promise<string> => {
    try {
        const data = {name: "allowme", kind: "ip", description: "Generated by AllowMe"}
        const res = await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists`, "POST", data)

        logger.info("Cloudflare.createList", res.id)
        return res.id
    } catch (ex) {
        logger.error("Cloudflare.createList", ex)
    }
}

/**
 * Get firewall rule ID from Cloudflare.
 */
export const getFirewallId = async (): Promise<string> => {
    try {
        const res: any[] = await makeRequest(`zones/${settings.cloudflare.zoneId}/firewall/rules`)
        const rule = res.find((i) => i.action == "allow" && i.filter.expression.includes("ip.src in $allowme"))

        if (rule) {
            logger.info("Cloudflare.getFirewallId", rule.id)
            return rule.id
        } else {
            const ruleId = await createFirewall()
            logger.info("Cloudflare.getFirewallId", ruleId)
            return ruleId
        }
    } catch (ex) {
        logger.error("Cloudflare.getFirewallId", ex)
    }
}

/**
 * Create an "AllowMe" firewall rule on Cloudflare.
 */
export const createFirewall = async (): Promise<string> => {
    try {
        const filter = {expression: `ip.src in $${settings.cloudflare.listName}`}
        const data = [{priority: 1, action: "allow", filter: filter, description: "Generated by AllowMe"}]
        const res = await makeRequest(`zones/${settings.cloudflare.zoneId}/firewall/rules`, "POST", data)
        const id = res[0].id

        logger.info("Cloudflare.createFirewall", id)
        return id
    } catch (ex) {
        logger.error("Cloudflare.createFirewall", ex)
    }
}

/**
 * Add the specified IP to the allow list.
 * Will throw an exception if it fails.
 */
export const ipAllow = async (ip: string): Promise<boolean> => {
    try {
        if (ip == "::1") {
            logger.warn("Cloudflare.ipAllow", ip, "Local IP, won't be added")
            return false
        }

        const items = await getListItems()

        if (items.find((i) => i.ip == ip)) {
            logger.warn("Cloudflare.ipAllow", ip, "Already on the list")
            return false
        }

        const data = [{ip: ip, comment: "AllowMe"}]
        await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists/${settings.cloudflare.listId}/items`, "POST", data)

        logger.info("Cloudflare.ipAllow", ip)
        return true
    } catch (ex) {
        logger.error("Cloudflare.ipAllow", ip, ex)
        throw ex
    }
}

/**
 * Remove the specified IP from the allow list.
 * Will throw an exception if it fails.
 */
export const ipBlock = async (ip: string): Promise<boolean> => {
    try {
        if (ip == "::1") {
            logger.warn("Cloudflare.ipBlock", ip, "Local IP, won't be removed")
            return false
        }

        const items = await getListItems()
        const ipItem = items.find((i) => i.ip == ip)

        if (!ipItem) {
            logger.warn("Cloudflare.ipBlock", ip, "Not on the list")
            return false
        }

        const data = {items: [{id: ipItem.id}]}
        await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists/${settings.cloudflare.listId}/items`, "DELETE", data)

        logger.info("Cloudflare.ipBlock", ip, `Removed ${ipItem.id}`)
        return true
    } catch (ex) {
        logger.error("Cloudflare.ipBlock", ip, ex)
        throw ex
    }
}

/**
 * Auto remove expired IPs from the list.
 */
export const cleanup = async (): Promise<void> => {
    try {
        const now = new Date().valueOf()
        const age = parseInt(settings.ip.maxAge) * 1000 * 60
        const data = {items: []}

        // Fetch and process list of IPs.
        const items = await getListItems()

        for (let item of items) {
            if (item.comment == "AllowMe") {
                const created = new Date(item.created_on).valueOf()

                // Too old? Mark the IP for removal.
                if (now - age > created) {
                    data.items.push({id: item.id})
                    logger.info("Cloudflare.cleanup", item.ip, "Will be removed")
                }
            }
        }

        if (data.items.length > 0) {
            await makeRequest(`accounts/${settings.cloudflare.accountId}/rules/lists/${settings.cloudflare.listId}/items`, "DELETE", data)
            logger.info("Cloudflare.cleanup", `Removed ${data.items.length} IP(s)`)
        }
    } catch (ex) {
        logger.error("Cloudflare.cleanup", ex)
    }
}

/**
 * Helper to make requests to the Cloudflare API.
 * @param path API path.
 * @param method Supported methods: GET, POST, DELETE.
 * @param body Request body to be posted.
 */
const makeRequest = async (path: string, method?: "GET" | "POST" | "DELETE", body?: any): Promise<any> => {
    try {
        const options: AxiosRequestConfig = {
            method: method || "GET",
            headers: {Authorization: `Bearer ${settings.cloudflare.token}`}
        }
        if (body) {
            options.data = body
        }

        const res = await axios(`https://api.cloudflare.com/client/v4/${path}`, options)

        if (res.data && res.data.result) {
            return res.data.result
        } else if (!body) {
            throw new Error(`Invalid data: ${path}`)
        }
    } catch (ex) {
        if (ex.response) {
            const details = ex.response.data && ex.response.data.errors ? ex.response.data.errors.map((e) => e.message).join(" | ") : ex.message
            throw new Error(`${ex.response.status} - ${details}`)
        } else {
            throw ex
        }
    }
}
